# JioTV Go Configuration

# Enable EPG (Electronic Program Guide)
epg = true

# Enable Debug Mode
debug = true

# Enable DRM (Digital Rights Management)
drm = true

# TS Handler (set to true to disable, false to enable)
disable_ts_handler = false

# Logout Feature (set to true to disable, false to enable)
disable_logout = true

# URL Encryption (set to true to disable, false to enable)
disable_url_encryption = false

# Title of the webpage
title = "Jio+"

# Log to Stdout
log_to_stdout = true

# Proxy URL (uncomment and set if needed)
# proxy = "socks5://user:pass@host:port"

# Log Path (leave empty for default)
# log_path = ""

# Custom Channels File
custom_channels_file = "custom_channels.json"
